#The convention YAML files should be start with --- always, to accomplish with the recommended practice.
#The comments start with # how would files in Linux, every play muts contain a set of hosts and a list of task to be execute on those hosts.
#Think and keep simple (T&KS), the Playbook has this goal. Try with RHEL 7.x
---
- hosts: all
  remote_user: root
  # Can you use variables, identity with vars:
  tasks: #Updating the system, the name lists all the packages and checking that ultimate version state
  - redhat_subscription:
        state: present
        username: someuser
        password: anypasswd
  - name: Manage repos
    shell: |
            subscription-manager attach --pool=8a85f98157083df101570b65bfd10580
            subscription-manager repos --disable=*
            subscription-manager repos --enable=rhel-7-server-rpms
    when:  ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 7
    #Update system
  - yum:
      name: '*'
      state: latest
...
