#The convention YAML files should be start with --- always, to accomplish with the recommended practice.
#The comments start with # how would files in Linux, every play muts contain a set of hosts and a list of task to be execute on those hosts.
#Think and keep simple (T&KS), the Playbook has this goal. Try with RHEL 7.x
---
- hosts: all
  remote_user: root
  vars_prompt:
          - name: "rhtuser"
            prompt: "Ingresa tu usuario"
            private: no
          - name: "contra"
            prompt: "Ingresa tu contrasena"
            private: yes
  tasks: #Updating the system, the name lists all the packages and checking that ultimate version state
  - redhat_subscription:
        state: present
        username: "{{ rhtuser }}"
        password: "{{ contra }}"
  - name: Manage repos
    shell: |
            subscription-manager attach --pool=9a67f9815ab905d3015ab928c7005de4
            subscription-manager repos --disable=*
            subscription-manager repos --enable=rhel-7-server-rpms
    when:  ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
    #Update system
  - yum:
      name: '*'
      state: latest
...
