---
# Check file and copy content to web site 
- hosts: all
  remote_user: root

  tasks:
          - name: Download main file
            get_url:
                    url: http://clau.larenata.int/files/index.html
                    dest: /var/www/html/
                    checksum: sha256:19c7b7241fbbc903dfc41841ec3e4a103413037948352802a250fa806aa68d38
          - name: Copy file
            copy:
                    src: opt/images/BankIto.png
                    dest: /var/www/html/images/BankIto.png
                    owner: apache
                    group: apache

...
