---
# Update all packages related with Web Server
- hosts: all
  remote_user: root

  tasks:
          - name: Update
            yum:
                    name: "@Basic Web Server"
                    state: latest
#          - name: Check service
#            systemd:
#                    name: httpd
#                    state: restarted
#                    daemon_reload: yes
#                    enabled: yes

...
